version: "3.5"

services:
  api-scaffold:
    image: sndregistry.sondeosglobal.com/ciudadano/api-scaffold:tagname
    container_name: api-scaffold
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./.env:/app/.env
    ports:
      - "8080:8080"
