version: "3.5"

services:
  api-scaffold:
    image: api-scaffold:tagname
    container_name: api-scaffold
    volumes:
      - ./media:/app/media
      - ./logs:/app/logs
      - ./.env:/app/.env
    ports:
      - "5000:5000"
